### ISSUE TITLE
Convert v0 CEs to v1

### ISSUE THREAD

**Issue by priley86** [patternfly-webcomponents/patternfly-webcomponents#27]
This will involve adopting the latest polyfill and converting all v0 CEs to v1 specification

**Comment by Agathver** [comment]
I was reading through the [specs](https://www.w3.org/TR/custom-elements/) and [MDN](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Custom_Elements) and looks like it is not much work in adopting the source code, while there are not many components to change.

**Comment by priley86** [comment]
@Agathver if you would like to try this out, please for go it! We will want to update the polyfill dependency and update the lifecycles (like you mentioned). I am hearing there may be a few bugs still in v1 (since it is so new), but we can surely test this out. Bleeding edge!

Let me know if I can help, but if you want to take a stab at this, feel free @Agathver !

**Comment by Agathver** [comment]
> According to the spec, Custom Elements must be ES6 classes (https://html.spec.whatwg.org/multipage/scripting.html#custom-element-conformance).
https://github.com/webcomponents/webcomponentsjs

This is what they people say.

Custom Elements v1 are slowly landing across browsers and since we too are moving to Custom Elements v1 soon, we may need to rethink the packaging process that happens by webpack and babel, before switching to CEv1.

Polymer website mentions Safari Tech Preview and Chrome throw errors when CE v1 elements are used using ES5 Syntax.
