### ISSUE TITLE
clean up custom event names

### ISSUE THREAD

**Issue by priley86** [patternfly-webcomponents/patternfly-webcomponents#35]
Let's standardize on a common naming convention for custom events. This conversation is already started in #33. This issue will help resolve that problem and ensure we have consistently named events globally (across all components).

**Comment by priley86** [comment]
@sahil143 - since you are awesome and already finished the pf-dropdown, would this be something you might be interested in helping out with?

I know you are also catching up to speed on the Angular and React demo apps/framework shims. If you want to balance this item with that one, let me know! I think this one should be a bit easier once we decide on a convention.

**Comment by sahil143** [comment]
I would be glad to help out on this one. Any ideas on naming convention other than "show.pf.*"?

**Comment by sahil143** [comment]
**Slack Discussion on Naming convention**
@sahil143: Based on this issue #35  adopt a naming convention globally for custom events. This conversation already started in Pf-modal PR and it has been already suggested in pf-modal PR by @dabeng to use `show.pf.modal` instead of `show.bs.modal` as `bs` is for bootstrap. I think this is a good starting point. 
We can also consider to use hierarchical naming convention `pf.componentname.customevent`/`pfcomponentnamecustomevent`(I prefer dot convention because it is easy to understand) i.e. `pf.modal.show`/`pfmodalshow` this will also help in set custom events name for components like list-view(`pf.listview.rowselected`)  which don't have bootstrap naming ......
 Pros: 
1.) will help in long run: suppose two components have `initialized` event then we can differentiate b/w them..... like `pf.dropdown.initialized`  and `pf.accordion.initialized`
 2.) easy to understand and set new names for events easily  .....
.Cons: 
 1.) Custom events may have longer names. 
Any thoughts on this or new ideas... All are welcome.
@priley86 : great summary @sahil143 … @bleathem @dana @dlabrecq any thoughts on event naming convention before @sahil143 gets going? would :heart: some comments in this issue :slightly_smiling_face:
@dlabrecq : I'd like to use the component name as the prefix (e.g., 'pf-list-view.show' instead of 'pf.list-view.show') Or pf-utilization-bar-chart.show
@bleathem: indeed, nice summary.  I like the dot notation vs. the lack of dots. +1 @dlabrecq for using the component name.

**Comment by priley86** [comment]
For specific events, I tend to prefer `show.pf.modal` and the `shown.pf.modal` naming convention to mimic [bootstraps api](https://v4-alpha.getbootstrap.com/components/modal/#how-it-works). This tends to be more declarative and consistent with Bootstrap and would be fairly easy for a consumer to digest. 

However, for web component [lifecycle events](https://rawgit.com/priley86/devnexus-2017/master/demo/index.html#7), such as `created`, `attached`, `disconnected` etc., I'd prefer a common naming convention to be used in **all** web components (which can easily be identified). We used `initialized` so far in some components to indicate the attached method finished (because that event name is common in other frameworks), but i'm not opposed to making this `attached` or something more specific.

This is my $.02. I am completely open to ideas on this and thrilled we are arriving on a standard!

**Comment by Agathver** [comment]
One of the goals of custom components are to be reusable, and IMO, the same should apply to API structure as well.

Some of the events such as `show` are essentially raised by a lot of components. Instead of grouping all events using an element specific namespace like `show.pf.modal` and `show.pf.accordion`, we can consider some of the events as standard events that should be same across all components.

The previous two can be conveniently replaced with `pf.component.show`.

**Comment by dabeng** [comment]
Is there final convention about custom events?

**Comment by priley86** [comment]
per #33 I'd propose to stick w/ @dlabrecq's suggestion `<pf-componentname>.<eventname>`. This will be shorter and represent what we want for each component.

for [v0 lifecycle events](https://rawgit.com/priley86/devnexus-2017/master/demo/index.html#7), in cases where desired i'd propose we fire the following (at the end of each method):
createdCallback: `created`
attachedCallback: `initialized`
detachedCallback: `disconnected`
attributeChangedCallback: `[attributeName]Changed`

My thinking w/ this is we can then use similar names after moving to v1 spec (and thus save effort):
constructor: `created`
connectedCallback: `initialized`
disconnectedCallback: `disconnected`
attributeChangedCallback: `[attributeName]Changed`
adoptedCallback: `adopted`

thoughts on this @dlabrecq @sahil143 @Agathver @bleathem ?

**Comment by Agathver** [comment]
> per #33 I'd propose to stick w/ @dlabrecq's suggestion <pf-componentname>.<eventname>. This will be shorter and represent what we want for each component.

@priley86 We will have to consider the fact that dot conveys special meaning during declarative initialization of some frameworks. I suggest hyphenated names instead. 

Also, we should probably put all our events withing the `pf-` namespace so as to avoid any collision between any other frameworks. This includes the life cycle events too.

**Comment by priley86** [comment]
Hey @Agathver, I think the collision issue really comes down to how you are intending to use the event. My expectation is that these will not be consumed globally but rather on a per element basis. I.e.: 
let myCE = document.querySelector('the-ce');
myCE.addEventListener('initialized', () => {});

Scoping your listeners/handlers per component is still common amongst most frameworks. The only issue for collision I'd see is when you are expecting that a consumer might be sharing the same DOM element w/ a another plugin (which could allow for collision I suppose). For this reason I'd be OK w/ prefixing, but I wouldn't say this is common (even amongst other framework components I've seen).

**Comment by priley86** [comment]
Good discussion here b.t.w. ;)

**Comment by Agathver** [comment]
>The only issue for collision I'd see is when you are expecting that a consumer might be sharing the same DOM element w/ a another plugin... 

I recall using a jQuery plugin that used to fire `initialized` event on the element it was called upon. 😅

**Comment by priley86** [comment]
Thanks for the feedback here @Agathver . Yes, it's a good point (and I guess this possibility exists)...`initialized` is short and easier to type (thus my preference there), but to be extra cautious we can prefix. So I suppose our updated proposal would be:

`<pf-componentname>.<eventname>` will be used for all specific component events.

for v0 lifecycle events:
createdCallback: `<pf-componentname>.created`
attachedCallback: `<pf-componentname>.initialized`
detachedCallback: `<pf-componentname>.disconnected`
attributeChangedCallback: `<pf-componentname>.[attributeName]Changed`

My thinking w/ this is we can then use similar names after moving to v1 spec (and thus save effort):
constructor: `<pf-componentname>.created`
connectedCallback: `<pf-componentname>.initialized`
disconnectedCallback: `<pf-componentname>.disconnected`
attributeChangedCallback: `<pf-componentname>.[attributeName]Changed`
adoptedCallback: `<pf-componentname>.adopted`

**Comment by bleathem** [comment]
:+1: I like where this proposal has settled.  I'm happy to proceed with the above suggestion.

**Comment by priley86** [comment]
resolve in #64
